### ISSUE TITLE
2 questions about paper

### ISSUE THREAD

**Issue by imdoublecats** [Kent0n-Li/FGDM#2]
thank you for your work, but i have two questions.
1.how did fig2 in the paper generated, the frequency img and the real img seems not match when i reproduce the method, or that just a kind of schematic img?
2.in hpf, in the paper eta is 10, but when i reproduce, i_mag of ct ranges from 0 to 3 around, 10 is too large.i also clip HU -1000-1000, and normalized to 0-1, and use a slice of lung ct.

**Comment by Kent0n-Li** [comment]
It is a kind of schematic image. In HPF, it is by Gaussian filtering reduces the overall high-frequency intensity and then filtered according to the intensity threshold. If you have any further questions, please contact me at yunxiang.li@utsouthwestern.edu
