### ISSUE TITLE
problems of the data

### ISSUE THREAD

**Issue by duoqingxiaowangzi** [Kent0n-Li/FGDM#3]
![image](https://github.com/Kent0n-Li/FGDM/assets/117001352/c6105f5e-6709-4474-909f-ec00effdd6f2)
Hello author, may I ask why the data you are processing is single channel?

**Comment by Kent0n-Li** [comment]
It is CT or MRI Image with only one channel.

**Comment by duoqingxiaowangzi** [comment]
If I want to process images with three channels, do I just need to change the number of channels in the model, or do I need to make major changes within the model

**Comment by Kent0n-Li** [comment]
The input of Sobel filter should be one channel, as for the model input, u can directly modify it into 3.
